language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn clean source:jar deploy --settings travis_settings.xml

# travis encrypt -r bootique/bootique-kafka-client "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r bootique/bootique-kafka-client "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "lCWRvBVZWGnwOXui0uwD2ZMMWE3QQ4Wq1Qc3TxzlKmZsagqr7n0By8A/m/60ccZr8z/iF+8LXey4md1RMyh9eOZBpDxwXXIYO7mPkOLIGI6snZwrOTKtspvxAQvDaTlOhRHqKLyJ/xhDdVGqMU0Vxw1GgXqUMbbQFXliDS5M+zpPKMYQy2hKqT9+gxS8uz11wd73ficWmCs59u9JFVvRaBHxQUiQXKZ+r/R7zp7WTTi5zP6ywqzmKvRvNckO6BqFBltt8p+svF4iLqc7iMiIMjU/ZogjIR5Ht1SyegeUm3WHyNRu5vi+jh2I0OOho/RRKVs3K4Q99bjV4R4DFIUYHsz3RIOLF/hMr7IUxX0UUEPCGXm6t22H8XjSIuLTYwfk99/huupfOs5jjQgY1hngWvzBXYqx2Ba4Sx07vgL9tdsHbLOQgJGhpWjLQT+gMOwVxiGD7y4vvKVZAbc2eo2eQ2EU+KUoh6bBSKtwipW9g4K1AAK52d0HAdrz9EBV1rrLb/IhcTn5PM9VSf+0VdfokIxyQEojdqC/cWuGRk4mqJtQY4xOoKDGYVFIHpppJ+e6RvNx1J36f20X5AVRUgyoeNBP5L4p6wVkeF4OYOFdIV5NG+dO2IIgK81i9yKvvsrTF2ma0xBuALxFGztArN3pNjS7lqg9S52tYFqPZ9ShRXw="
    - secure: "fU8+RGsBeBKBmd/cxG3yWs+kKi1YkMPrqCway2DkyjpJHx/0nLTwstpz5k7BaeEnXN72UrmkamZjH1N41S48Js7PDEvihFnr2ppGfMs8QkbInD7P0W8kWz7YQH288CAPyMWimNBmftWxy8fH/0FFZ/h+rID3Ti6B69gNQ2IEVxqVnSga8t55W2LIiKamf7OQG8+hHBtIuUYfBWlcNI1QuBMQK8ZsseGzMk0h4ffRxyjCEhiyVn17rQPKMC48gBZNLnlgy+zcPYJ3HaROGq+ufMpsEU6K7aHtPGyuax1fxC62zRov+4537p2KmAVZ6151Ii1SFCJiQReyqKFhTfPiCQkAVhGS888SX1MPdqhSbIm6zC2ZpgeRRCYvGZTR/ZfhBdEHz/5Ad62Z3NG9HIksZtrRbuhJ2cJbEoCZSHXyz3i7NoPV3W7Vqu4IT250Lg3KsxIA0jai3+ThHc/NTpT5Rdzwuux051CyD5ATUao4fOagLwTS7szlBKrNaQWZlpFHCSzzsYPPh1QAXnqHb8H5JiUGXBs7NYMSkoKC3dOfXKOMaf/hCV9RnSvo33L8I+dzdSR9Z1l3CUigT/gL6LpninEW5kRElnWvVoVeSmir1gGwIqnHdvMqYhRDfSPWpby9bjXVXZ+mcnuPD4K46g1O13vRCd7vZzmKXsIOJG8mqW0="

